openapi: 3.0.0
info:
  title: REST API Mahasiswa
  description: Dokumentasi REST API untuk pengelolaan data mahasiswa.
  version: 1.0.0

paths:
  /data:
    get:
      summary: Mengambil semua data mahasiswa
      responses:
        '200':
          description: Berhasil mengambil data mahasiswa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mahasiswa'
    post:
      summary: Menambahkan data mahasiswa baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MahasiswaInput'
      responses:
        '200':
          description: Berhasil menambahkan data mahasiswa
        '400':
          description: Data Mahasiswa tidak lengkap
  /data/{id}:
    get:
      summary: Mengambil data mahasiswa berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID mahasiswa yang ingin diambil
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil mengambil data mahasiswa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mahasiswa'
    put:
      summary: Memperbarui data mahasiswa berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID mahasiswa yang ingin diperbarui
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MahasiswaInput'
      responses:
        '200':
          description: Berhasil memperbarui data mahasiswa
        '400':
          description: Data Mahasiswa tidak lengkap
    delete:
      summary: Menghapus data mahasiswa berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID mahasiswa yang ingin dihapus
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil menghapus data mahasiswa
components:
  schemas:
    Mahasiswa:
      type: object
      properties:
        id:
          type: integer
        nama:
          type: string
        no_telepon:
          type: string
        alamat:
          type: string
    MahasiswaInput:
      type: object
      required:
        - nama
        - no_telepon
        - alamat
      properties:
        nama:
          type: string
        no_telepon:
          type: string
        alamat:
          type: string
